# USB
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PID=0x0004
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y

# # Peripherals
CONFIG_GPIO=y
CONFIG_I2C=y

# # Sensors
CONFIG_SENSOR=y
CONFIG_BMI270=y

# # debug
# CONFIG_LOG=y
# CONFIG_SENSOR_LOG_LEVEL_DBG=y
# CONFIG_I2C_LOG_LEVEL_DBG=y

# added to ease communication with the computer api
CONFIG_BOOT_BANNER=n